using System;
using System.Collections.Generic;

public class NameGen
{
    private List<string> prefixes;
    private List<string> suffixes;
    
    private static NameGen _instance;
    public static NameGen Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = new NameGen();
            }
            return _instance;
        }
    }
    public NameGen()
    {
        prefixes = new List<string>
        {
            "Tech",
            "Info",
            "Data",
            "Net",
            "Sys",
            "Global",
            "Next",
            "Future",
            "Prime",
            "Alpha",
            "Sanford and Sons",
            "Bixby Bros.",
            "Angel",
            "Next Level",
            "Joe's",
            "Al's",
            "Bob's",
            "Karen & Karen",
            "CIA Front",
            "Hey Zeus",
            "Mr. E",
            "Misstress Rebecca's",
            "Tiger Tony",
            "Genie",
            "Shutoku",
            "C1",
            "Yokohama",
            "Crystal",
            "Fried Liver",
            "Gluk Gluk",
            "Base 7",
            "Number 8",
            "First Blow",
            "Stephen Segal",
            "Horny Toad",
            "Glass Cannon",
            "Barbara's",
            "Babar the Elephant",
            "Red Dragon",
            "Blue Dragon",
            "Golden Dragon",
            "Tarnished Dragon",
            "D'Balzee",
            "Les Infants Terribles",
            "Scene Kids",
            "Gothic G",
            "Baldies",
            "Punk Poser",
            "Emo Elite",
            "Cyber Crew",
            "Neon Green",
            "LSD Wash",
            "Frippertronics",
            "Quantum Foam",
            "Emo Matter",
            "Phase 0 Energy",
            "Diguised Delegations",
            "The",
            "Deez Knutz",
            "Das Machinen Ist N�t",
            "Scheisty",
            "Shell Corp",
            "Nein Nein Shasta!",
            "Morb in Time",
            "Ein Bier Bitte",
            "Matrix at Home",
            "Last Gasp",
            "Little Gophers",
            "Hamster Dance",
            "Pepe'n Shotty",
            "Aquire & Destroy",
            "Ribbed for Displeasure",
            "Jason & the Travelling Circus",
            "Matt's Funk",
            "Weedle, Deedle and Wee",
            "The Firm",
            "Invasive",
            "Silky Lubrih Creation",
            "Lubi Crate",
            "Fancy Pants",
            "Short & Sweet",
            "The Endgame Crew",
            "Jolly Rogers",
            "Roger Hermom",
            "Epic Ween",
            "Gogmazios",
            "Bert, Ernie & Cocaine",
            "Kermit's Finger",
            "Trash Police",
            "Purrfect",
            "Non Non Biyori",
            "Blasted Boris",
            "Rocky, Bullwinkle, Natasha & Boris",
            "Stupid Alarm",
            "Local Panic",
            "The Jimmy Hendrix Experience",
            "Electric Gypsy Jazz",
            "Cruisin' for a Bruisin'",
            "Kwik Release",
            "Connect 42",
            "Trans Atlantic & Some Other Places",
            "Plant-Based",
            "Dapper Dan's",
            "Open Sorcery",
            "Mystic Farts",
            "Fully Loaded",
            "Yellow Snow",
            "Cold, Tired & Hungry",
            "Big Fat",
            "MOAR!!!",
            "Lots of Tongue",
            "Extra Crispy",
            "Fully Inserted",
            "Deep Dish",
            "French Kissed the Frog",
            "Yokel",
            "Hillbilly",
            "Redneck Rose's",
            "Trailer Park",
            "Double-Wide",
            "Double-Blind",
            "Blindsided",
            "Backline",
            "Amateur Hour",
            "Dead Man's",
            "Final Notice",
            "Lounge Lizards",
            "Jabba's",
            "Jingo Jane's",
            "Captain's",
            "Private Reserve",
            "Secret Stash",
            "Lost Treasures",
            "Furriers",
            "Large Marsupials",
            "Satin & Silk",
            "Velvet",
            "Grade B",
            "Rotten Core",
            "Healthy Glow",
            "Axe & Shield",
            "My Very Own",
            "Super Duper",
            "Bigly Smart",
            "Frantic",
            "Hyper Drive",
            "Gumball",
            "Under the Influence",
            "Round & Round",
            "Rince & Repeat",
            "Astronomically Priced",
            "Double Triple",
            "Slicked Back",
            "Virtual",
            "Frank's",
            "Je Ne Sais Quoi",
            "Cognitive",
            "Homebrew",
            "Homemade",
            "Handcrafted by Grannies",
            "Best by Test",
            "Completely Average",
            "Mediocre",
            "Quack",
            "Milquetoast",
            "Unpleasant",
            "Dubious & Questionable",
            "Totally Real",
            "Legit",
            "Awesomesauce",
            "Nothingburger",
            "Kissing Cousins",
            "Mustache",
            "El Gringo's",
            "Don Quixote's",
            "Old Hippies",
            "Art is Dead",
            "Funky Monks",
            "Groovy",
            "Matt Damon",
            "Tiny Problem",
            "Partial Solutions",
            "Old Lady",
            "On Pace Alone",
            "Burnt Out",
            "Half-Cocked",
            "Semi-Pro",
            "Do It Manually",
            "Gorgeous George's",
            "Greasy",
            "John Doe's",
            "We Do It",
            "Free Range",
            "Unhinged",
            "Grass-Fed",
            "Sketchy",
            "Magic",
            "Rainbows & Unicorns",
            "Annoying Sprite",
            "Johnny Orangeseed",
            "Premature",
            "Early Adoption",
            "Deep-Fried",
            "Finger Lickin'",
            "Colonel Mustard",
            "Evil",
            "Down With",
            "Virtuoso",
            "Wile E.",
            "Reverse",
            "Faux",
            "Imitation",
            "Replica",
            "Bonafide Certified Bootleg",
            "Genuine",
            "Certified",
            "Gauranteed OK",
            "X-treme Team",
            "Pre-Owned",
            "Third-Hand",
            "Used but Good",
            "Green Man Group",
            "Jabberwock & Daughters",
            "His Holiness",
            "Sacred Cow",
            "Divine Conceptions",
            "Holy Rollers",
            "Redacted",
            "Classified Top Secret",
            "Undisclosed Locations",
            "Area 52",
            "Hop Along",
            "Special",
            "Extra Extra",
            "Unlimited Editions",
            "Preliminary Decisions",
            "Revenge Plan",
            "Contingency",
            "Git Gud",
            "Gaseous",
            "Infinite Rabbits",
            "720 No Scope",
            "Four-Twenty",
            "Dewey Decimal",
            "Schitt, Schitt & Schitt" };
        
        suffixes = new List<string>
        { 
            "Solutions",
            "Systems",
            "Technologies",
            "Corporation",
            "Enterprises",
            "Dynamics",
            "Innovations",
            "Labs",
            "Works",
            "Studios",
            "Foundations",
            "Factories",
            "Trucking",
            "Warehouses",
            "Shipping",
            "Investments",
            "Crime Scene Cleaners",
            "Jeans and Denim-wear",
            "Dude Ranch",
            "Emporium",
            "Construction",
            "Maintenance",
            "Consulting",
            "Associates",
            "Partners",
            "Group",
            "Collective",
            "Syndicate",
            "Consortium",
            "Alliance",
            "Coalition",
            "Federation",
            "Union",
            "Conglomerate",
            "Holdings",
            "Industries",
            "Manufacturing",
            "Productions",
            "Outfitters",
            "Esquire",
            "Fusion",
            "Nuclear",
            "Armaments",
            "Ammunition & Child Care",
            "Funeral Parlors Chain",
            "Wash & Go",
            "Massage Parlours",
            "Tanning Salons",
            "Spray Tan Studios",
            "Hair Removal Services",
            "Toupees & Hair Extensions",
            "Wig Emporium",
            "Pet Grooming",
            "Billiards Halls",
            "Arcade Systems",
            "VHS Rentals",
            "Evergreening",
            "Lizard Breeders",
            "Exotic Animal Traders",
            "Tattoo Parlors",
            "Body Piercing Studios",
            "Custom Motorcycle Shops",
            "Bakery",
            "Caf�s & Car Repair Shops",
            "Scottish Fine Cousine",
            "Sheep Sheering Services",
            "Haggis Suppliers to the Queen",
            "Highland Games Organization",
            "Glass Blowers",
            "Left Handed Scissors Mfctrs",
            "Organic Candlebra Specialists",
            "Wind Chime Artisans",
            "Bohemian Soapmakers",
            "Artisanal Cheese Mongers",
            "Vintage Typewriter Repair",
            "Bagel Artisans",
            "Half-Door Manufacturing",
            "Custom Toothpick Appreciation Society",
            "Bedazzler Supplies",
            "Turtle Painters",
            "Eggbeater Repair",
            "Professional Cuddlers",
            "Mime Amplification Corp.",
            "Physchic Consultants",
            "Dream Interpreters",
            "Japanese/Klingon Translation Services",
            "Detective Agency",
            "Ghost Hunters",
            "House Renos & Reposessions",
            "Antique Restoration and Destruction",
            "Used Grater Dealers",
            "Custom Snow Globe Makers",
            "Handmade Doorknob Retailers",
            "Specialty Plunger Suppliers",
            "Emergency Clown Response Team",
            "Organic Mustache Wax",
            "Vintage Sock Puppets",
            "Yodeling Instructors",
            "Tutoring",
            "Mustache Groomers",
            "Open Source",
            "Bicycle Manufacturering",
            "Nanotech",
            "Miniaturization",
            "Robotic Prosthetics for Pets",
            "AI De-integration",
            "Brain-Computer Interfaces",
            "Realty Ltd.",
            "Estate Agents",
            "Property Management",
            "Tractors & Heavy Machinery",
            "Farm Equipment",
            "Agricultural Supplies",
            "Lawn Mowing Services",
            "Landscaping & Tree Surgery",
            "Driving Instructors",
            "Racing Schools",
            "Nurburg Ring Taxi Services",
            "Twitch Streamers Union",
            "Esports Teams",
            "Amateur Radio Repair",
            "Casinos & Gaming",
            "Crime Syndicate",
            "Smuggling Operations",
            "Bootlegging & Speakeasies",
            "Pirate Radio Stations",
            "Underground Fight Clubs",
            "Black Market Organ Dealers",
            "Illicit Substance Distributors",
            "Counterfeit Memorabilia",
            "Forgery Services",
            "Underground Casinos",
            "Treasure Hunters Guild",
            "Custom Fur Suits",
            "Calligraphy Studios",
            "Illuminated Manuscripts",
            "Medieval Reenactment Supplies",
            "MegaCorp",
            "International",
            "Pizzaria",
            "Brewery",
            "Crude Oil Refining",
            "Nervous Energy Solutions",
            "High Voltage Systems",
            "Plasma Tech",
            "Frozen Foods",
            "Klip'n Kurl",
            "Waifu Wraps",
            "Robotics for Infants",
            "Refrigeration and Horoscopes",
            "Bypass Construction",
            "Comb-Over Repair",
            "Synthetic Organics",
            "Haute Couture",
            "Private Investigations",
            "Insecurity Services",
            "Paranormal Security",
            "Cryptid Containment",
            "Alien Abduction Recovery",
            "UFO Sightings Verification",
            "Extraterrestrial Relations",
            "Interdimensional Travel Agents",
            "Time Travel Logistics",
            "Chrono-Couriers",
            "Temporal Mechanics",
            "Anachronism Removal Services",
            "Continuum Stabilization",
            "Paradox Resolution",
            "Mental Augmentation",
            "Behavioral Modification",
            "Pyramid Scheme Consultants",
            "Expertise Brokers",
            "Influence Peddling",
            "Artisanal Black Market",
            "Rare Artifact Dealers",
            "Underground Auctioneers",
            "Shadow Economy Analysts",
            "Covert Operations",
            "Espionage Services",
            "Clandestine Communications",
            "Surveillance Solutions",
            "Counterintelligence",
            "Stealth Technology",
            "Finest Quality Chotchkes",
            "Novelty Item Brokerage",
            "Medical Supply House",
            "Bros.",
            "Mortuary Services",
            "Reaping Services",
            "Marijuana Horticulture",
            "Timeshares",
            "Call Centers",
            "Equine Transportation",
            "Used Toothpaste Vendors",
            "Dehydrated Water Suppliers",
            "Pre-Owned Air Sellers",
            "Expertise",
            "House Flippers",
            "Taco Truck",
            "Printer Disposal Services",
            "Debuggers",
            "Mustard",
            "Plinko Parlours",
            "Bubble-Tea",
            "Sock Kiosks",
            "Sushi",
            "Debt Collection",
            "Secret Base Construction",
            "Exterminators",
            "Pest Control",
            "Biohazard Clean",
            "Bomb Disposal",
            "Flak Guns"
        };
    }
    public string GenerateRandomCompanyName()
    {
        Random random = MyRandom.Instance;
        string prefix = prefixes[random.Next(prefixes.Count)];
        string suffix = suffixes[random.Next(suffixes.Count)];
        return prefix + " " + suffix;
    }
}
